spring:
  application:
    name: hotel-microservice

# MySQL Database Configuration

  datasource:
    url: jdbc:mysql://localhost:3306/hoteldata?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# Hibernate JPA Configuration

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
